# Generated by Django 3.2.3 on 2021-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['name'],
            },
        ),
    ]
